name: build-and-test
run-name: ${{ github.actor }} building and testing
on: [push]
jobs:
  check-bats-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest
      - run: npm ci --legacy-peer-deps
      # - run: cd ios && pod install
      - shell: bash
          run: npx react-native start --sourceExts mock.js,js,json,ts,tsx
      # - run: npx react-native start --sourceExts mock.js,js,json,ts,tsx
      - run: detox test --configuration ios.sim.debug


