name: build-and-test
run-name: ${{ github.actor }} building and testing
on: [push]
jobs:
  check-bats-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest
      - run: npm install --legacy-peer-deps
      - run: cd ios && pod install
      - run: npm test